<a href="https://colab.research.google.com/github/Oguzhan-Sevim/PuzzleSolution/blob/master/puzzle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**A Puzzle**

Three players A, B, C play the following game. First, A picks a real number between 0 and 1 (both inclusive), then B picks a number in the same range (different from A’s choice) and finally C picks a number, also in the same range, (different from the two chosen numbers). We then pick a number in the range uniformly randomly. Whoever’s number is closest to this random number wins the game. Assume that A, B and C all play optimally and their sole goal is to maximise their chances of winning. Also assume that if one of them has several optimal choices, then that player will randomly pick one of the optimal choices.

Can you write a program to figure out the best choice for the first player when the game is played among four players?

In [1]:
import numpy as np

In [2]:
def winning_prob(values):
  # This function takes the choices of players as input and returns
  # the winning probabilities of agents for their chosen values.
  # e.g. [0.05, 0.35, 0.55, 0.95] would corresponds winning chances of [0.2, 0.25, 0.3, 0.25]
  temp = sorted(values)
  order = [temp.index(i) for i in values]

  returns = [0, 0, 0, 0]

  returns[order.index(0)] = round( values[order.index(0)] + (values[order.index(1)] - values[order.index(0)]) / 2 , 3)
  returns[order.index(1)] = round( (values[order.index(2)] - values[order.index(0)]) / 2 , 3)
  returns[order.index(2)] = round( (values[order.index(3)] - values[order.index(1)]) / 2 , 3)
  returns[order.index(3)] = round( ( 1 - values[order.index(3)] ) + (values[order.index(3)] - values[order.index(2)]) / 2 , 3)
      
  return returns

In [4]:
# Check if the probability calculator works correctly:
test_list = [0.05, 0.35, 0.55, 0.95]
test_list2 = [0.48, 0.84, 0.18, 0.5]
print( winning_prob(test_list) )

[0.2, 0.25, 0.3, 0.25]


In [ ]:
# Discretize interval 0-1 by the desired step size. Then, create an array
# that has all scenarios.  
step_size = 2 * 10**-2 # choose it wisely

choices = np.arange(0, 1+step_size, step_size).astype(np.float16)
len = choices.shape[0]

a = np.repeat(choices, len**3)
a = np.reshape(a, (a.shape[0], 1))

b = np.repeat(choices, len**2)
b = np.tile(b, len)
b = np.reshape(b, (b.shape[0], 1))

c = np.repeat(choices, len)
c = np.tile(c, len**2)
c = np.reshape(c, (c.shape[0], 1))

d = np.tile(choices, len**3)
d = np.reshape(d, (d.shape[0], 1))

all_possibilities = np.concatenate((a,b,c,d), axis=1)

del a, b, c, d

print(all_possibilities.shape, all_possibilities.dtype)

(6765201, 4) float16


In [ ]:
# First clear all states where any 2 players make the same choice:
del_index = []

for i in range(all_possibilities.shape[0]):
  if np.unique(all_possibilities[i,:], axis=0).shape[0] != 4:
    del_index.append(i)

all_possibilities = np.delete(all_possibilities, del_index, axis=0)

del del_index

print(all_possibilities.shape, all_possibilities.dtype)

(5997600, 4) float16


In [ ]:
# Clear illogical choices for player d:
player_index = 3

previous_players_hold = all_possibilities[0,0:player_index]
best_return = 0
keep_index = []
keep_index_temp = []

for i in range(all_possibilities.shape[0]):
  if np.array_equal(all_possibilities[i,0:player_index], previous_players_hold):
    returns = winning_prob(all_possibilities[i,:].tolist())
    if returns[player_index] > best_return:
      best_return = returns[player_index]
      keep_index_temp = [i]
    elif returns[player_index] == best_return:
      keep_index_temp = keep_index_temp + [i]
  else:
    keep_index = keep_index + keep_index_temp
    keep_index_temp = [i]

    returns = winning_prob(all_possibilities[i,:].tolist())
    best_return = returns[player_index]
    previous_players_hold = all_possibilities[i,0:player_index]
    

all_possibilities = all_possibilities[keep_index, :]

print(all_possibilities.shape, all_possibilities.dtype)

(1184855, 4) float16


In [ ]:
# Clear illogical choices for player c:
player_index = 2

previous_players_hold = all_possibilities[0,0:player_index]
best_return = 0
keep_index = []
keep_index_temp = []

for i in range(all_possibilities.shape[0]):
  if np.array_equal(all_possibilities[i,0:player_index], previous_players_hold):
    returns = winning_prob(all_possibilities[i,:].tolist())
    if returns[player_index] > best_return:
      best_return = returns[player_index]
      keep_index_temp = [i]
    elif returns[player_index] == best_return:
      keep_index_temp = keep_index_temp + [i]
  else:
    keep_index = keep_index + keep_index_temp
    keep_index_temp = [i]

    returns = winning_prob(all_possibilities[i,:].tolist())
    best_return = returns[player_index]
    previous_players_hold = all_possibilities[i,0:player_index]
    

all_possibilities = all_possibilities[keep_index, :]

print(all_possibilities.shape)

(27215, 4)


In [ ]:
# Clear illogical choices for player b:
player_index = 1

previous_players_hold = all_possibilities[0,0:player_index]
best_return = 0
keep_index = []
keep_index_temp = []

for i in range(all_possibilities.shape[0]):
  if np.array_equal(all_possibilities[i,0:player_index], previous_players_hold):
    returns = winning_prob(all_possibilities[i,:].tolist())
    if returns[player_index] > best_return:
      best_return = returns[player_index]
      keep_index_temp = [i]
    elif returns[player_index] == best_return:
      keep_index_temp = keep_index_temp + [i]
  else:
    keep_index = keep_index + keep_index_temp
    keep_index_temp = [i]

    returns = winning_prob(all_possibilities[i,:].tolist())
    best_return = returns[player_index]
    previous_players_hold = all_possibilities[i,0:player_index]
    
all_possibilities = all_possibilities[keep_index, :]

print(all_possibilities.shape)

(61, 4)


In [ ]:
# Check the returns of player a:
for i in range(all_possibilities.shape[0]):
  returns = winning_prob(all_possibilities[i,:].tolist())
  print(all_possibilities[i,:], returns)

[0.   0.8  0.4  0.02] [0.01, 0.4, 0.39, 0.2]
[0.02 0.8  0.42 0.04] [0.03, 0.39, 0.38, 0.2]
[0.04 0.42 0.8  0.06] [0.05, 0.37, 0.39, 0.19]
[0.04 0.44 0.8  0.06] [0.05, 0.37, 0.38, 0.2]
[0.04 0.82 0.44 0.06] [0.05, 0.37, 0.38, 0.2]
[0.06 0.82 0.44 0.08] [0.07, 0.37, 0.37, 0.19]
[0.08 0.82 0.46 0.1 ] [0.09, 0.36, 0.36, 0.19]
[0.1  0.82 0.46 0.12] [0.11, 0.36, 0.35, 0.18]
[0.12 0.82 0.48 0.14] [0.13, 0.35, 0.34, 0.18]
[0.14 0.48 0.82 0.16] [0.15, 0.33, 0.35, 0.17]
[0.14 0.5  0.82 0.16] [0.15, 0.33, 0.34, 0.18]
[0.14 0.84 0.5  0.16] [0.15, 0.33, 0.34, 0.18]
[0.16 0.84 0.5  0.18] [0.17, 0.33, 0.33, 0.17]
[0.18 0.82 0.48 0.16] [0.16, 0.35, 0.32, 0.17]
[0.2  0.8  0.42 0.18] [0.12, 0.39, 0.3, 0.19]
[0.22 0.78 0.36 0.2 ] [0.08, 0.43, 0.28, 0.21]
[0.24 0.76 0.3  0.22] [0.04, 0.47, 0.26, 0.23]
[0.26 0.76 0.24 0.28] [0.02, 0.48, 0.25, 0.25]
[0.26 0.76 0.28 0.24] [0.02, 0.48, 0.25, 0.25]
[0.28 0.76 0.24 0.3 ] [0.03, 0.47, 0.26, 0.24]
[0.3  0.76 0.24 0.32] [0.04, 0.46, 0.27, 0.23]
[0.32 0.78 0.24 0.3

In [ ]:
# Find the best choice for player a:
player_index = 0

keep_index = []
best_return = 0

for i in range(all_possibilities.shape[0]):
  returns = winning_prob(all_possibilities[i,:].tolist())
  if returns[player_index] > best_return:
    best_return = returns[player_index]
    keep_index = [i]
  elif returns[player_index] == best_return:
    keep_index = keep_index + [i]

all_possibilities = all_possibilities[keep_index, :]

print(all_possibilities.shape)

(4, 4) float16


In [ ]:
# Check the best moves and returns of player a:
for i in range(all_possibilities.shape[0]):
  returns = winning_prob(all_possibilities[i,:].tolist())
  print(all_possibilities[i,:], returns)

[0.16 0.84 0.5  0.18] [0.17, 0.33, 0.33, 0.17]
[0.5  0.16 0.82 0.48] [0.17, 0.32, 0.34, 0.17]
[0.5  0.84 0.18 0.52] [0.17, 0.32, 0.34, 0.17]
[0.84 0.16 0.5  0.82] [0.17, 0.33, 0.33, 0.17]
